### ISSUE TITLE
Celery crash if bad sending domain

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#1363]
## Describe the bug 

Celery crashes if a service has their sending domain set to one that's not in our verified list

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

SEV-4 Low

## To Reproduce

1. Set your sending domain to something invalid (ex: stevespizza.com)
2. Send an email
3. See a celery error similar to
```
Traceback (most recent call last):
  File "/app/app/clients/email/aws_ses.py", line 104, in send_email
    response = self._client.send_raw_email(Source=source, RawMessage={"Data": msg.as_string()})
  File "/app/.venv/lib/python3.10/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/app/.venv/lib/python3.10/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.MessageRejected: An error occurred (MessageRejected) when calling the SendRawEmail operation: Email address is not verified. The following identities failed the check in region CA-CENTRAL-1: Service <service@stevespizza.com>...
```

## Expected behavior

- Celery doesn't crash
- would be nice if the log pointed out the problem better
- bonus points would be not letting an admin put in an invalid sending domain in the first place. Sinice only an admin can make this change this would probably be more work than its worth.

## Impact

- Confusing error
- emails don't send if this is set wrong

**Comment by andrewleith** [comment]
Note: there is a 5 minute cache on the list of sending domains, so when a new one is added, it will take 5 minutes for it to show up in the list.
