### ISSUE TITLE
Flaky test: Set transaction timeout 

### ISSUE THREAD

**Issue by iokpala** [cds-snc/notification-planning#185]
Flaky test: Set transaction timeout 

### Task Description

There appears to be a chain of ignored database migrations. 

When `flask db migrate` is run.. the following file is generated

```
"""

Revision ID: 4a88a36b2669
Revises: 0325_set_transaction_timeout
Create Date: 2021-11-18 11:01:01.369519

"""
from alembic import op  # isort:skip
import sqlalchemy as sa  # isort:skip
from sqlalchemy.dialects import postgresql  # isort:skip

revision = "4a88a36b2669"
down_revision = "0325_set_transaction_timeout"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "complaints", "notification_history", ["notification_id"], ["id"])
    op.alter_column("dm_datetime", "month_name", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.alter_column("dm_datetime", "quartal", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.alter_column("dm_datetime", "week_day_name", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.alter_column("dm_datetime", "year_calendar_week", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.alter_column("dm_datetime", "year_month", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.alter_column("dm_datetime", "year_quartal", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.create_index(op.f("ix_fido2_sessions_user_id"), "fido2_sessions", ["user_id"], unique=True)
    op.alter_column("notification_history", "international", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "notification_history", "notification_status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True
    )
    op.alter_column(
        "notification_history", "rate_multiplier", existing_type=sa.NUMERIC(), type_=sa.Float(), existing_nullable=True
    )
    op.alter_column("notifications", "international", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("notifications", "notification_status", existing_type=sa.TEXT(), type_=sa.String(), existing_nullable=True)
    op.alter_column("notifications", "rate_multiplier", existing_type=sa.NUMERIC(), type_=sa.Float(), existing_nullable=True)
    op.drop_index("ix_notifications_service_created_at", table_name="notifications")
    op.alter_column(
        "organisation",
        "default_branding_is_french",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("rates", "rate", existing_type=sa.NUMERIC(), type_=sa.Float(), existing_nullable=False)
    op.drop_index("ix_service_whitelist_service_id", table_name="service_safelist")
    op.create_index(op.f("ix_service_safelist_service_id"), "service_safelist", ["service_id"], unique=False)
    op.alter_column(
        "services",
        "default_branding_is_french",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("services", "sending_domain", existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=True)
    op.alter_column(
        "services_history",
        "default_branding_is_french",
        existing_type=sa.BOOLEAN(),
        nullable=False,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("services_history", "prefix_sms", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column(
        "services_history", "sending_domain", existing_type=sa.TEXT(), type_=sa.String(length=255), existing_nullable=True
    )
    op.alter_column("user_to_service", "service_id", existing_type=postgresql.UUID(), nullable=False)
    op.alter_column("user_to_service", "user_id", existing_type=postgresql.UUID(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user_to_service", "user_id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column("user_to_service", "service_id", existing_type=postgresql.UUID(), nullable=True)
    op.alter_column(
        "services_history", "sending_domain", existing_type=sa.String(length=255), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column("services_history", "prefix_sms", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "services_history",
        "default_branding_is_french",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.alter_column("services", "sending_domain", existing_type=sa.String(length=255), type_=sa.TEXT(), existing_nullable=True)
    op.alter_column(
        "services",
        "default_branding_is_french",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.drop_index(op.f("ix_service_safelist_service_id"), table_name="service_safelist")
    op.create_index("ix_service_whitelist_service_id", "service_safelist", ["service_id"], unique=False)
    op.alter_column("rates", "rate", existing_type=sa.Float(), type_=sa.NUMERIC(), existing_nullable=False)
    op.alter_column(
        "organisation",
        "default_branding_is_french",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("false"),
    )
    op.create_index("ix_notifications_service_created_at", "notifications", ["service_id", "created_at"], unique=False)
    op.alter_column("notifications", "rate_multiplier", existing_type=sa.Float(), type_=sa.NUMERIC(), existing_nullable=True)
    op.alter_column("notifications", "notification_status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True)
    op.alter_column("notifications", "international", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column(
        "notification_history", "rate_multiplier", existing_type=sa.Float(), type_=sa.NUMERIC(), existing_nullable=True
    )
    op.alter_column(
        "notification_history", "notification_status", existing_type=sa.String(), type_=sa.TEXT(), existing_nullable=True
    )
    op.alter_column("notification_history", "international", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_index(op.f("ix_fido2_sessions_user_id"), table_name="fido2_sessions")
    op.alter_column("dm_datetime", "year_quartal", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.alter_column("dm_datetime", "year_month", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.alter_column("dm_datetime", "year_calendar_week", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.alter_column("dm_datetime", "week_day_name", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.alter_column("dm_datetime", "quartal", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.alter_column("dm_datetime", "month_name", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    op.drop_constraint(None, "complaints", type_="foreignkey")
    # ### end Alembic commands ###

```

### Task Outcome

Ensure clear benchmarks for regression tracking during development.

### Acceptance Criteria
- [ ] Tests are passing post `flask db migrate` on local and remote instances.

**Comment by jimleroyer** [comment]
It's not clear to me what is the error message or which tests fail from this.

**Comment by iokpala** [comment]
Sorry Jimmy.. My bad.. 

```
 flask db upgrade
2021-11-22T18:22:33 api api INFO no-request-id "Logging configured" [in /Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/notifications_utils/logging.py:78]
Traceback (most recent call last):
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.NotNullViolation: column "prefix_sms" of relation "services_history" contains null values


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ikenna/.virtualenvs/notifications-api/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/flask_migrate/cli.py", line 136, in upgrade
    _upgrade(directory, revision, sql, tag, x_arg)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/flask_migrate/__init__.py", line 271, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/command.py", line 294, in upgrade
    script.run_env()
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/script/base.py", line 490, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/util/pyfiles.py", line 97, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/util/compat.py", line 182, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "migrations/env.py", line 76, in <module>
    run_migrations_online()
  File "migrations/env.py", line 68, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/runtime/environment.py", line 813, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/runtime/migration.py", line 560, in run_migrations
    step.migration_fn(**kw)
  File "/Users/ikenna/repo/cds/notify/api/migrations/versions/30ec6e837bfb_.py", line 62, in upgrade
    op.alter_column("services_history", "prefix_sms", existing_type=sa.BOOLEAN(), nullable=False)
  File "<string>", line 8, in alter_column
  File "<string>", line 3, in alter_column
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/operations/ops.py", line 1612, in alter_column
    return operations.invoke(alt)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/operations/base.py", line 354, in invoke
    return fn(self, operation)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/operations/toimpl.py", line 43, in alter_column
    operations.impl.alter_column(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/ddl/postgresql.py", line 141, in alter_column
    super(PostgresqlImpl, self).alter_column(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/ddl/impl.py", line 175, in alter_column
    self._exec(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/alembic/ddl/impl.py", line 146, in _exec
    return conn.execute(construct, multiparams)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/ikenna/.virtualenvs/notifications-api/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.errors.NotNullViolation) column "prefix_sms" of relation "services_history" contains null values

[SQL: ALTER TABLE services_history ALTER COLUMN prefix_sms SET NOT NULL]
(Background on this error at: http://sqlalche.me/e/13/gkpj)

```

**Comment by yaelberger-commits** [comment]
@iokpala does this bug still apply? 
@sastels has this been fixed as far as you know?

**Comment by sastels** [comment]
I haven't looked at this
