### ISSUE TITLE
Using JWT with api can raise uncaught server errors

### ISSUE THREAD

**Issue by sastels** [cds-snc/notification-planning#818]
## Describe the bug 

A service tried using JWTs in their api requests, causing uncaught `TokenAlgorithmError` errors

## [Bug Severity](https://docs.google.com/document/d/1tcD32bjJRaREsMgaUEoXAk400y1dKzzaKR0G5Sr1w20/edit)
See examples in the documentation

(SEV-1 Critical, SEV-2 Major, SEV-3 Minor, SEV-4 Low) 
SEV-3 ? can trigger OpsGenie, and we probably don't send back a meaningful error message

## To Reproduce

Try to use a bad JWT with api

## Expected behavior

api handles the error by sending back an error message and does not crash.

## Impact

CDS staff: can trigger Alerts
Service owners: can get back unhelpful error messages

## Additional context

[Incident report](https://docs.google.com/document/d/1OKit0HZLcA-gbSVzu5yiSXC5GDoV-2skSawkl8Lma0s/edit#)
```
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/notifications_python_client/authentication.py", line 97, in decode_jwt_token
decoded_token = jwt.decode(
File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 90, in decode_complete
decoded = api_jws.decode_complete(
File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 149, in decode_complete
self._verify_signature(signing_input, header, signature, key, algorithms)
File "/usr/local/lib/python3.9/site-packages/jwt/api_jws.py", line 229, in _verify_signature
raise InvalidAlgorithmError("The specified alg value is not allowed")
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed
```

**Comment by yaelberger-commits** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Notify-Planning-614b3ad91bc2030015ed22f5/issues/cds-snc/notification-planning/818?planning-poker) with Zenhub @andrewleith @jimleroyer @jzbahrai @sastels
